version: '3'
services:
  backend:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - 'apps:/home/frappe/frappe-bench/apps'
      - 'assets:/home/frappe/frappe-bench/sites/assets'
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  configurator:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - '-c'
    command:
      - "ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache \"redis://$$REDIS_CACHE\"; bench set-config -g redis_queue \"redis://$$REDIS_QUEUE\"; bench set-config -g redis_socketio \"redis://$$REDIS_QUEUE\"; bench set-config -gp socketio_port $$SOCKETIO_PORT;\n"
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      REDIS_CACHE: 'redis-cache:6379'
      REDIS_QUEUE: 'redis-queue:6379'
      SOCKETIO_PORT: '9000'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  create-site:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: none
    volumes:
      - 'apps:/home/frappe/frappe-bench/apps'
      - 'assets:/home/frappe/frappe-bench/sites/assets'
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
    entrypoint:
      - bash
      - '-c'
    command:
      - "wait-for-it -t 120 db:3306; wait-for-it -t 120 redis-cache:6379; wait-for-it -t 120 redis-queue:6379; export start=`date +%s`; until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".db_host // empty\"` ]] && \\\n  [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".redis_cache // empty\"` ]] && \\\n  [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".redis_queue // empty\"` ]];\ndo\n  echo \"Waiting for sites/common_site_config.json to be created\";\n  sleep 5;\n  if (( `date +%s`-start > 120 )); then\n    echo \"could not find sites/common_site_config.json with required keys\";\n    exit 1\n  fi\ndone; echo \"sites/common_site_config.json found\"; bench get-app builder; bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default frontend;\n bench --site frontend install-app builder;"
  db:
    image: 'mariadb:10.6'
    healthcheck:
      test: 'mysqladmin ping -h localhost --password=admin'
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--skip-innodb-read-only-compressed'
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - 'db-data:/var/lib/mysql'
  frontend:
    image: 'frappe/erpnext:v15.19.1'
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: 'backend:8000'
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: 'websocket:9000'
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: 'off'
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - 'apps:/home/frappe/frappe-bench/apps'
      - 'assets:/home/frappe/frappe-bench/sites/assets'
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
    ports:
      - '8083:8080'
  queue-long:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - '--queue'
      - 'long,default,short'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  queue-short:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - '--queue'
      - 'short,default'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  redis-queue:
    image: 'redis:6.2-alpine'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - 'redis-queue-data:/data'
  redis-cache:
    image: 'redis:6.2-alpine'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - 'redis-cache-data:/data'
  scheduler:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  websocket:
    image: 'frappe/erpnext:v15.19.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
volumes:
  db-data: null
  redis-queue-data: null
  redis-cache-data: null
  apps: null
  assets: null
  sites: null
  logs: null
